# Generated by Django 3.2.6 on 2022-05-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_flutter_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
