# Generated by Django 3.2.6 on 2022-05-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fullstack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
